print('Programmu izstrādāja: Jēkabs, Vallis.')
print('')
print('Laukuma aprēķins ģeometriskām figūrām')
print('    ****')
print('Ievadiet malas A garumu:')
a = input()
a = int(a)
print('Malas A garums: ',float(a))
print('    ****')
print('Ievadiet malas B garumu:')
b = input()
b = int(b)
print('Malas B garums: ',float(b))
print('    ****')
print('Ievadiet augstumu:')
h = input()
h = int(h)
print('Augstums: ',float(h))
print('Laukums trijstūrim: ',(a*h)/2)
print('Laukums trapecei: ',((a+b)/2)*h)
print('Laukums paralelogramam: ',float(a*h))
print('    ****')
print('Paldies!')